version: "3.3"
services:
  nginx:
    container_name: nginx
    build: docker/nginx
    command: nginx -g "daemon off;"
    links:
      - php
    ports:
      - "80:80"
    depends_on:
      - php
  php:
    container_name: php
    build: docker/php
    tty: true
    volumes:
      - ./:/var/www/html/app
    working_dir: /var/www/html/app/public
    ports:
      - "9000"