version: "3.3"
services:
  nginx:
    container_name: nginx
    build: docker/nginx
    command: nginx -g "daemon off;"
    links:
      - php
    ports:
      - "80:80"
  php:
    container_name: php
    build: docker/php
    volumes:
      - ./src:/var/www/html/app
    working_dir: /var/www/html/app/public
    command: php-fpm
    ports:
      - "9000:9000"